# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-18 11:39
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mac_address', models.CharField(max_length=16)),
                ('serial_number', models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='제품이름')),
                ('price', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(-1)], verbose_name='제품가격')),
                ('status', models.IntegerField(choices=[(0, '준비중'), (1, '생산중'), (2, '단종됨')], default=0)),
            ],
        ),
        migrations.AddField(
            model_name='device',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Product'),
        ),
    ]
